---
ci:
    autoupdate_schedule: quarterly

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
          - id: no-commit-to-branch
          - id: check-docstring-first
          - id: end-of-file-fixer
          - id: check-merge-conflict
          - id: check-yaml

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.9.0
      hooks:
          - id: ruff
            args: [--fix]
          - id: ruff-format

    - repo: https://github.com/kynan/nbstripout
      rev: 0.7.1
      hooks:
          - id: nbstripout

    - repo: https://github.com/astral-sh/ty-pre-commit
      rev: v0.9.9
      hooks:
          - id: ty

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.35.1
      hooks:
          - id: yamllint
