---
ci:
    autoupdate_schedule: quarterly

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: trailing-whitespace
          - id: no-commit-to-branch
          - id: check-docstring-first
          - id: end-of-file-fixer
          - id: check-merge-conflict
          - id: check-yaml

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.15.20
      hooks:
          - id: ruff
            args: [--fix]
          - id: ruff-format

    - repo: https://github.com/kynan/nbstripout
      rev: 0.9.1
      hooks:
          - id: nbstripout

    - repo: https://github.com/hoxbro/ty-pre-commit
      rev: v0.0.56
      hooks:
          - id: ty-check

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.38.0
      hooks:
          - id: yamllint
