---
name: remote_climate_data-dev
channels:
  - conda-forge
dependencies:
  - python=3.8
  - intake
  - xarray
  - pandas==1.3.0
  - intake-xarray
  - intake-thredds
  - geopandas
  - regionmask
  - intake-geopandas
  - pydap
  - h5netcdf
  - netcdf4
  - rioxarray
  - fsspec
  - aiohttp
  - pytest
  - pytest-sugar
  - pre-commit
  - jupyterlab
  # Visualization
  - matplotlib-base
  - nc-time-axis
  - cartopy
  - geoviews
  - hvplot
  - xrviz
  - pip
  - pip:  # get latest master from source
      - git+https://github.com/edjdavid/intake-excel.git
      - openpyxl
      #- xlrd==1.2.0  # newer versions dont support xlsx
      - -e .
