name: remote_climate_data-dev
channels:
  - conda-forge
dependencies:  # requred: mean required for catalog to load data
  - python=3.6
  - intake  # requred
  - xarray  # requred
  - dask  # requred
  - fsspec  # requred
  - requests
  - geopandas  # requred
  - ipywidgets
  - aiohttp  # fsspec or dask should actually include this
  # Visualization
  - cartopy
  - matplotlib
  - pyviz_comms
  - hvplot
  - geoviews
  - bokeh
  - pip
  - pip:  # get latest master from source
      - git+https://github.com/intake/filesystem_spec.git  # required
      - git+https://github.com/intake/intake.git  # requred
      - git+https://github.com/intake/intake-xarray.git  # requred
      - git+https://github.com/mathause/regionmask.git
      - git+https://github.com/intake/intake-esm.git
      - git+https://github.com/aaronspring/intake_geopandas.git@AS_cache  # requred
