name: remote_climate_data-dev
channels:
  - conda-forge
dependencies:
  - python=3.6
  - intake
  - xarray
  - pydap
  - dask
  - h5netcdf
  - fsspec
  - requests
  - aiohttp
  - geopandas
  - regionmask
  - pip
  # Currently 5.4.0 or greater breaks pytest-sugar. It looks like this will be fixed
  # soon and we can revert back to the newest pytest.
  # https://github.com/Teemu/pytest-sugar/issues/187
  - pytest<5.4.0
  - pytest-cov
  - pytest-sugar
  - pre-commit
  # Visualization
  - cartopy
  - matplotlib
  - nc-time-axis
  - pyviz_comms
  - hvplot
  - ipywidgets
  - nodejs
  - dask-labextension
  - pip:  # get latest master from source
      - git+https://github.com/intake/filesystem_spec.git
      - git+https://github.com/edjdavid/intake-excel.git
      - xlrd==1.2.0  # newer versions dont support xlsx
      - git+https://github.com/intake/intake-xarray.git
      - git+https://github.com/NCAR/intake-thredds.git
      - git+https://github.com/geopandas/geopandas.git
      - git+https://github.com/intake/intake_geopandas.git # ordering is critical here, has to be last
