name: remote_climate_data-dev
channels:
  - pyviz
  - conda-forge
dependencies:
  - python=3.9
  - intake[dataframe]
  - xarray
  - intake-xarray
  - intake-thredds
  - pydap
  - dask-core
  - h5netcdf
  - netcdf4
  - fsspec
  - requests
  - aiohttp
  - importlib_metadata
  - pyarrow
  - geopandas
  - intake_geopandas
  - regionmask
  - pytest
  - pytest-sugar
  - pre-commit
  # Visualization
  - cartopy
  - matplotlib
  - nc-time-axis
  - pyviz_comms
  - jupyter_bokeh
  - hvplot
  - panel
  - xrviz
  - geoviews
  - holoviews
  - jupyter-server-proxy
  - ipywidgets
  - nodejs
  - dask-labextension
  - pip
  - pip:  # get latest master from source
      - git+https://github.com/edjdavid/intake-excel.git
      - openpyxl
      - xlrd==1.2.0  # newer versions dont support xlsx
