name: remote_climate_data-dev
channels:
  - conda-forge
dependencies:
  - python=3.8
  - intake[dataframe]
  - xarray
  - intake-xarray
  - intake-thredds
  - pydap
  - dask
  - h5netcdf
  - fsspec==0.8.7
  - requests
  - aiohttp
  - importlib_metadata
  - pyarrow
  - geopandas
  - regionmask
  - pytest
  - pytest-cov
  - pytest-sugar
  - pre-commit
  # Visualization
  - cartopy
  - matplotlib
  - nc-time-axis
  - pyviz_comms
  - hvplot==0.7.0
  - jupyter-server-proxy
  - ipywidgets
  - nodejs
  - dask-labextension
  - dfviz
  - xrviz
  - pip
  - pip:  # get latest master from source
      - git+https://github.com/edjdavid/intake-excel.git
      - xlrd==1.2.0  # newer versions dont support xlsx
      - intake_geopandas
