---
name: remote_climate_data-dev
channels:
  - conda-forge
dependencies:
  - python=3.12
  - setuptools<70
  - intake<2
  - intake-thredds=2024.3.1
  - xarray
  - pandas
  - intake-xarray
  - intake-thredds
  - geopandas
  - regionmask
  - intake-geopandas
  - pydap
  - h5netcdf
  - netcdf4
  - rioxarray
  - fsspec
  - aiohttp
  - requests
  - pytest
  - pytest-sugar
  - pytest-xdist
  - prek
  - ruff
  - jupyterlab
  # Visualization
  - matplotlib-base
  - nc-time-axis
  - cartopy
  - geoviews
  - hvplot
  - pip
  - pip:
      - -e .
