---
name: remote_climate_data-dev
channels:
  - conda-forge
dependencies:
  - python=3.12
  - intake>=2
  - xarray
  - pandas
  - intake-xarray>=2.0.0
  - geopandas
  - regionmask
  - intake-geopandas
  - pydap
  - h5netcdf
  - h5py
  - rioxarray
  - fsspec
  - scipy
  - aiohttp
  - requests
  - pytest
  - pytest-sugar
  - pytest-xdist
  - prek
  - ruff
  - jupyterlab
  # Visualization
  - matplotlib-base
  - nc-time-axis
  - cartopy
  - geoviews
  - hvplot
  - pip
  - pip:
      - -e .
