name: remote_climate_data-dev
channels:
  - conda-forge
dependencies:
  - python=3.8
  - intake[dataframe]
  - xarray
  - intake-xarray
  - intake-thredds
  - pydap
  - dask-core
  - h5netcdf
  - netcdf4
  - fsspec
  - requests
  - aiohttp
  - geopandas
  - intake-geopandas
  - regionmask
  - pytest
  - pytest-sugar
  - pre-commit
  # Visualization
  - matplotlib-base
  - nc-time-axis
  - cartopy
  - geoviews
  - hvplot
  - xrviz
  - pip
  - pip:  # get latest master from source
      - git+https://github.com/edjdavid/intake-excel.git
      - openpyxl
      - xlrd==1.2.0  # newer versions dont support xlsx
