name: remote_climate_data-dev
channels:
  - conda-forge
dependencies:
  - python=3.6
  - intake
  - xarray
  - dask
  - fsspec
  - requests
  - intake-xarray
  - intake-esm
  - geopandas
  - ipywidgets
  # Visualization
  - cartopy
  - matplotlib
  - hvplot
  - bokeh
  - pip
  - pip:  # get latest master from source
      - git+https://github.com/intake/filesystem_spec.git
      - git+https://github.com/intake/intake.git
      - git+https://github.com/intake/intake-xarray.git
      - git+https://github.com/mathause/regionmask.git
      - git+https://github.com/intake/intake-esm.git
      - git+https://github.com/intake/intake_geopandas.git
