name: remote_climate_data-dev
channels:
  - conda-forge
dependencies:
  - python=3.6
  - intake
  - xarray
  - dask
  - fsspec
  - requests
  - aiohttp
  - geopandas
  - regionmask
  - pip
  - pytest
  - ipywidgets
  # Visualization
  - cartopy
  - matplotlib
  - pyviz_comms
  - hvplot
  #- geoviews
  - pip:  # get latest master from source
      - git+https://github.com/intake/filesystem_spec.git
      - git+https://github.com/intake/intake.git
      - git+https://github.com/intake/intake-xarray.git
      - git+https://github.com/geopandas/geopandas.git 
      - git+https://github.com/intake/intake_geopandas.git # ordering is critical here, has to be last
