---
name: remote_climate_data-binder
channels:
  - conda-forge
dependencies:
  - python=3.12
  - intake<2
  - intake-xarray
  - xarray
  - pandas
  - fsspec
  - aiohttp
  - h5netcdf
  - h5py
  - matplotlib-base
  - hvplot
  - jupyterlab
  - pip
  - pip:
      - -e ..
