name: binder PR link

on: pull_request

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
     
      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1
      - name: Echo the branch name
        run: echo "Branch name ${GIT_BRANCH_NAME}"

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Dynamic message your current branch is ${{ GIT_BRANCH_NAME }} or ${{ github.head_ref }}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
