name: comment binder PR link

on: [pull_request, push]

jobs:
  which_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # extract branch name
      - name: Extract branch name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo ${GITHUB_REF#refs/heads/}
