on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: get branch name
        run:
          BRANCH_NAME=${GITHUB_REF##*/}
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Try your PR on binder: ${{GITHUB_REF##*/}} ${{BRANCH_NAME}} https://mybinder.org/v2/gh/aaronspring/remote_climate_data/${{BRANCH_NAME}}?urlpath=lab?filepath=demo.ipynb!'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
