name: binder PR link

on: pull_request

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Dynamic message your current branch is ${{ github.head_ref }}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
