name: comment binder PR link

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - uses: nelonoel/branch-name@v1
    # Use branch name for whatever purpose
    - run: echo ${BRANCH_NAME}

          #message: 'Try your PR on binder: https://mybinder.org/v2/gh/aaronspring/remote_climate_data/BRANCH_NAME?urlpath=lab?filepath=demo.ipynb!'
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
