name: comment binder PR link

on: pull_request

jobs:
  comment_pr_for_binder:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Branch name
        run: |
          echo running on branch ${{ github.ref }}
          echo running on branch ${{ github.ref_head }}
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Try your PR on binder: https://mybinder.org/v2/gh/aaronspring/remote_climate_data/BRANCH_NAME?urlpath=lab?filepath=demo.ipynb!'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
