# This is a basic workflow to help you get started with Actions
name: testing

# Controls when the action will run.
on: pull_request


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    name: Test remote_climate_data
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python: [3.6]
      fail-fast: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge
          mamba-version: '*'
          activate-environment: remote_climate_data-dev
          python-version: 3.6
      - name: Set up conda environment
        run: |
          mamba env update -f environment.yml
      - name: Conda info
        run: conda info
      - name: Conda list
        run: conda list
      - name: get branch catalog
        run: |
          ls
          pwd
          echo $branch
          wget https://raw.githubusercontent.com/aaronspring/remote_climate_data/${{branch}}/master.yaml
          ls
      - name: Run tests
        run: |
          pytest

  test_notebooks:  # Checks that notebooks complete without failure.
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge
          mamba-version: '*'
          activate-environment: remote_climate_data-dev
          python-version: 3.6
      - name: Set up conda environment
        run: |
          mamba env update -f environment.yml
      - name: Conda info
        run: conda info
      - name: Conda list
        run: conda list
      - name: Test notebooks
        run: |
          jupyter nbconvert --inplace --execute notebooks/demo.ipynb
