---
name: testing

on:
  push:
  schedule:
    - cron: "0 0 * * 4"  # Thursdays "At 00:00" UTC
  workflow_dispatch:  # allows you to trigger manually

jobs:
  test_pytest:
    name: Test remote_climate_data
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python: ["3.12"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: false
          channels: conda-forge
          activate-environment: remote_climate_data-dev
          python-version: ${{ matrix.python }}
      - name: Set up conda environment
        run: |
          conda env update -f environment.yml
      - name: Conda info
        run: conda info
      - name: Conda list
        run: conda list
      - name: Run tests
        run: |
          pytest -n auto --durations=20

  test_notebooks:  # Checks that notebooks complete without failure.
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: false
          channels: conda-forge
          activate-environment: remote_climate_data-dev
          python-version: "3.12"
      - name: Set up conda environment
        run: |
          conda env update -f environment.yml
      - name: Conda info
        run: conda info
      - name: Conda list
        run: conda list
      - name: Test notebooks
        run: |
          jupyter nbconvert --inplace --execute notebooks/demo.ipynb
