---
name: testing

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 4"  # Thursdays “At 00:00” UTC
  workflow_dispatch:  # allows you to trigger manually

jobs:
  detect-ci-trigger:
    name: detect ci trigger
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    outputs:
      triggered: ${{ steps.detect-trigger.outputs.trigger-found }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: xarray-contrib/ci-trigger@v1.1
        id: detect-trigger
        with:
          keyword: "[skip-ci]"

  test_pytest:
    name: Test remote_climate_data
    needs: detect-ci-trigger
    if: needs.detect-ci-trigger.outputs.triggered == 'false'
    runs-on: macos-latest  # larger ram see
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python: [3.8]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          channels: conda-forge
          mamba-version: '*'
          activate-environment: remote_climate_data-dev
          python-version: 3.8
      - name: Set up conda environment
        run: |
          mamba env update -f environment.yml
      - name: Conda info
        run: conda info
      - name: Conda list
        run: conda list
      - name: Run tests
        run: |
          pytest --durations=20

  test_notebooks:  # Checks that notebooks complete without failure.
    runs-on: ubuntu-latest
    needs: detect-ci-trigger
    if: needs.detect-ci-trigger.outputs.triggered == 'false'
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          channels: conda-forge
          mamba-version: '*'
          activate-environment: remote_climate_data-dev
          python-version: 3.8
      - name: Set up conda environment
        run: |
          mamba env update -f environment.yml
      - name: Conda info
        run: conda info
      - name: Conda list
        run: conda list
      - name: Test notebooks
        run: |
          jupyter nbconvert --inplace --execute notebooks/demo.ipynb
