# This is a basic workflow to help you get started with Actions
name: testing

# Controls when the action will run. 
on: pull_request


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    name: Test remote_climate_data
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge
          mamba-version: '*'
          activate-environment: environment.yml
          python-version: 3.6
      - name: Set up conda environment
        run: |
          mamba env update -f environment.yml
          conda activate remote_climate_data-dev
          pip install pytest
      - name: Conda info
        run: conda info
      - name: Conda list
        run: conda list
      - name: Run tests
        run: |
          pytest
          
  docs_notebooks:  # Checks that pre-compiled notebooks in docs still work.
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge
          mamba-version: '*'
          activate-environment: environment.yml
          python-version: 3.6
      - name: Set up conda environment
        run: |
          mamba env update -f environment.yml
      - name: Conda info
        run: conda info
      - name: Conda list
        run: conda list
      - name: Test notebooks in docs
        run: |
          jupyter nbconvert --inplace --execute demo.ipynb
