---
name: testing

on:
  push:
  workflow_dispatch:  # allows you to trigger manually

jobs:
  test_pytest:
    name: Test remote_climate_data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Run tests
        run: uv run pytest -n auto --durations=20

  test_notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Test notebooks
        run: jupyter nbconvert --inplace --execute notebooks/demo.ipynb
